# Generated by Django 4.1.13 on 2024-01-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionhistory',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
