# Generated by Django 4.1.13 on 2024-01-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=10)),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('answer', models.IntegerField()),
            ],
        ),
    ]
