# Generated by Django 4.1.13 on 2024-01-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0002_resettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
