# Generated by Django 4.1.13 on 2024-01-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0002_question_user_alter_question_q_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizhistory',
            name='attempted_questions',
        ),
        migrations.RemoveField(
            model_name='quizhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuizHistory',
        ),
    ]
