# Generated by Django 4.1.13 on 2024-02-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='default_mail', max_length=254, unique=True)),
                ('reset_password_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
